<?php

function nypl_collections_menu() {

  $items['admin/config/collections'] = array(
    'title' => 'NYPL Collections Administration',
    'description' => '.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nypl_collections_settings'),
    'access arguments' => array('administer nypl_collections'),
    'file' => 'nypl_collections.admin.inc',
  );

  $items['admin/collection/currate'] = array(
    'title' => 'Curate a new Collection',
    'description' => 'Curate a new Collection.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nypl_collections_form'),
    'access arguments' => array('administer nypl_collections'),
    'file' => 'nypl_collections.admin.inc',
  );

  $items['collections/feed'] = array(
    'title' => 'NYPL Curated Collections Feed',
    'page callback' => 'nypl_collections_feed',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function nypl_collections_form() {

}